[package]
name = "bella"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ecs = "0.14.1"
crossbeam-queue = "0.3.11"
pollster = "0.3.0"
vello = { git = "https://github.com/linebender/vello/" }
winit = "0.30.5"